import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { useState } from 'react'
import loadable from '@loadable/component'


const Header = loadable(() => import('../components/Header'))
const Main = loadable(() => import('../components/Main'))


export default function Home() {

  const [search, setSearch] = useState('')

  const [filter, setFilter] = useState(null)



  return (
    <div id={styles.home}>
      <Head>
        <title>Star Wars</title>
        <meta name="description" content="Generated by create next app" />

      </Head>

      <Header search={search} setSearch={setSearch} setFilter={setFilter} filter={filter} />
      <Main search={search} filter={filter} />

    </div>
  )
}
